#!/usr/bin/env python3
"""Forward-subsumption experiment: guard the MITM forward closure so a candidate
theorem is dropped when an already-stored theorem at an equal-or-lower stratum
generalizes it (a most-general antichain per stratum prefix).

Soundness (bounded existence): if G at stratum g generalizes T at stratum s with
g <= s, any bounded proof using T at cost s can use G at cost g <= s instead, so
dropping T loses no reachable target. Realized through the kernel guard sink's
decimal-bound rule (drop when stored_bound >= candidate_bound) by storing
inverted strata: bound' = MAX_N - stratum, so stored' >= candidate' iff g <= s.

Index entries are guarded by the same key: if (G, g) covers (T, s), then any
candidate (C, c) covered by (T, s) -- T generalizes C, s <= c -- is covered by
(G, g) through transitivity and g <= s <= c, so dropping T's index entry is
complete.
"""

import subprocess
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
# Baseline fwd-only programs land next to the generated subsume variants;
# point MITM_DIR elsewhere to reuse existing baselines.
MITM = Path(os.environ.get("MITM_DIR", ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import build_mitm_programs as mitm  # noqa: E402

MAX_N = 26

FWD_SEED_IDX = """;; Subsumption index entries for the axiom seeds (stratum 1, inverted 25).
(fwdidx (→ $𝜑 (→ $𝜓 $𝜑)) 25)
(fwdidx (→ (→ $𝜑 (→ $𝜓 $𝜒))
           (→ (→ $𝜑 $𝜓) (→ $𝜑 $𝜒))) 25)
(fwdidx (→ (→ (¬ $𝜑) (¬ $𝜓))
           (→ $𝜓 $𝜑)) 25)
"""

GUARDED_FWD_CLOSURE_EXEC = """;; Forward closure with emit-time forward subsumption: the guard drops a
;; candidate theorem when a stored fwdidx schema at an equal-or-lower stratum
;; (inverted-bound comparison) generalizes it. The index insert is guarded by
;; the same key, keeping the index an antichain.
                  (exec (20 fwd-closure)
                        (, (fwd $fi (: $fp (→ $fa $fb)))
                           (addFn $fi $fj $fs_minus_one)
                           (incFn $fs_minus_one $fs)
                           (lte $fs {hf})
                           (invFn $fs $fsinv)
                           (fwd $fj (: $xp $fa)))
                        (O (guard (fwdidx $fb $fsinv) (fwd $fs (: (ax-mp $fp $xp) $fb)))
                           (guard (fwdidx $fb $fsinv) (fwdidx $fb $fsinv))))
                  """


def inv_table() -> str:
    lines = [
        ";; invFn S SINV with SINV = MAX - S: the guard sink drops when the stored",
        ";; bound is >= the candidate bound, so inverted strata make that test",
        ";; 'stored stratum <= candidate stratum', the sound subsumption direction.",
    ]
    for s in range(MAX_N + 1):
        lines.append(f"(invFn {s} {MAX_N - s})")
    return "\n".join(lines)


def render_forward_sub_only(hf: int) -> str:
    scheduler = mitm.static_scheduler(
        "$init_fuel", [GUARDED_FWD_CLOSURE_EXEC.format(hf=hf)]
    )
    return "\n".join(
        [
            ";; Generated by build_subsume_programs.py.",
            f";; Kind: forward-only with emit-time subsumption\n(forward-bound {hf})\n",
            mitm.LOAD_ARITH,
            mitm.arithmetic_tables(),
            inv_table(),
            "",
            mitm.FWD_SEEDS,
            FWD_SEED_IDX,
            f"""(scheduler-fuel {mitm.forward_fuel(hf)})

(exec (20 init-forward)
      (, (forward-bound $hf)
         (scheduler-fuel $init_fuel))
      (, {scheduler}))""",
            "",
        ]
    )


def write(name: str, text: str) -> Path:
    p = ROOT / name
    p.write_text(text)
    return p


def main() -> None:
    hfs = [int(a) for a in sys.argv[1:]] or [6, 7, 9, 11, 12]
    for hf in hfs:
        write(f"fwd-sub-only-hf{hf}.mm2", render_forward_sub_only(hf))
        baseline = MITM / f"fwd-only-hf{hf}.mm2"
        if not baseline.exists():
            write_path = MITM / f"fwd-only-hf{hf}.mm2"
            write_path.write_text(mitm.render_forward_only(hf))
        print(f"generated fwd-sub-only-hf{hf}.mm2 (baseline: {baseline.exists()})")


if __name__ == "__main__":
    main()
